# Generated by Django 2.1.3 on 2019-08-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertransaction',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
